trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

jobs:
- template: Source/DotNet/pipeline.yml@templates
  parameters:
    cascades:
      - 'dolittle-runtime/DotNET.SDK'      
      - 'dolittle-runtime/Runtime.Events.MongoDB'
      - 'dolittle-extensions/ReadModels.MongoDB'
